// <auto-generated />
using ListaWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ListaWeb.Migrations
{
    [DbContext(typeof(ListaDbContext))]
    [Migration("20180313164316_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("ListaWeb.Models.PendienteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("EstaHecha");

                    b.Property<DateTimeOffset?>("ParaCuando");

                    b.Property<string>("Pendiente");

                    b.HasKey("Id");

                    b.ToTable("Pendientes");
                });
#pragma warning restore 612, 618
        }
    }
}
